try
    print "In try block"
catch error
    print "In catch block"