# Test import + try-catch
import "test_module.zen"

set calc new Calculator

try
    print "In try block"
catch error
    print "Caught error:" error